apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
          - name: MYSQL_DATABASE
            value: votesDB
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_PASSWORD
            value: ""
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
