apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  # name: private-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
      # - name: private-reg-container
      # - name: vote
        # image: lillamiamy/build_something/vote
      - image: lillamiamy/build_something:vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
