apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
      # - name: worker
      #   image: lillamiamy/build_something/worker
      - image: lillamiamy/build_something:worker
        name: worker
